name: Build solution

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure .NET Core version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Test solution with dotnet
      run: dotnet test
    - name: Build solution with dotnet
      run: dotnet build --configuration Release
