name: Build solution

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Configure .NET Core version if needed
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
    - name: Test solution with dotnet
      run: dotnet test
    - name: Build solution with dotnet
      run: dotnet build --configuration Release
